.TH MYSTRCPY 3 "September 2026" "YEELELO OS Assignment" "Library Functions"

.SH NAME
mystrcpy \- copy a string to another string

.SH SYNOPSIS
.B #include "../include/mystrfunctions.h"

.B int mystrcpy(char *dest, const char *src);

.SH DESCRIPTION
The mystrcpy() function copies the string pointed to by
src into the destination string pointed to by dest.

.SH RETURN VALUE
The function returns the number of characters copied.

.SH AUTHOR
Faizan Bhatti
