.TH MYSTRLEN 3 "September 2026" "YEELELO OS Assignment" "Library Functions"

.SH NAME
mystrlen \- calculate the length of a string

.SH SYNOPSIS
.B #include "../include/mystrfunctions.h"

.B int mystrlen(const char *s);

.SH DESCRIPTION
The mystrlen() function calculates the number of characters
in the given string, excluding the terminating null character.

.SH RETURN VALUE
The function returns the length of the string.

.SH AUTHOR
Faizan Bhatti
