.TH MYSTRNCPY 3 "September 2026" "YEELELO OS Assignment" "Library Functions"

.SH NAME
mystrncpy \- copy a limited number of characters from a string

.SH SYNOPSIS
.B #include "../include/mystrfunctions.h"

.B int mystrncpy(char *dest, const char *src, int n);

.SH DESCRIPTION
The mystrncpy() function copies up to n characters
from the string pointed to by src into the destination
string pointed to by dest.

.SH RETURN VALUE
The function returns the number of characters processed.

.SH AUTHOR
Faizan Bhatti

