.TH MYSTRCAT 3 "September 2026" "YEELELO OS Assignment" "Library Functions"

.SH NAME
mystrcat \- concatenate two strings

.SH SYNOPSIS
.B #include "../include/mystrfunctions.h"

.B int mystrcat(char *dest, const char *src);

.SH DESCRIPTION
The mystrcat() function appends the string pointed to by
src to the end of the string pointed to by dest.

.SH RETURN VALUE
The function returns the length of the resulting string.

.SH AUTHOR
Faizan Bhatti
